---
layout: post
title: "Promise"
categories: ["JavaScript"]
---

Promise는 자바스크립트에서 비동기 처리를 위해 사용되는 객체이다.

#### Promise 객체를 쓰는 이유

- 비동기적으로 어떤 작업을 처리하기 위해
- 어떤 작업을 처리했을때 성공했는지 실패했는지 표준화된 방법으로 확인하기 위해

#### Promise의 처리 과정

Promise객체를 리턴하는 비동기 함수 호출
-> Promise객체는 **pending** 상태가 됨  
-> Promise객체가 **fulfilled** 상태가 되면 `then` 메서드로 등록한 콜백에서 프로미스 객체, 또는 일반적인 값을 리턴  
-> Promise객체가 **rejected** 상태가 되면 `catch` 메서드로 등록한 콜백에서 작업 실패 정보가 담긴 에러 객체를 리턴

#### Promise 객체가 가진 상태와 결과

- 이전 메서드의 콜백에서 **프로미스 객체를 반환했다면**  
  -> `then` 메서드가 리턴했던 프로미스 객체가 콜백이 리턴한 프로미스 객체의 상태와 결과를 똑같이 따라 갖게 된다.
- 이전 메서드의 콜백에서 프로미스 객체가 아닌 **일반적인 값을 반환했다면**  
  -> `then` 메서드가 리턴했던 프로미스 객체가 `fulfilled` 상태가 되고, 리턴된 값이 작업 성공 결과가 된다.
- 이전 메서드의 콜백에서 **아무것도 리턴하지 않았다면**  
  -> `then` 메서드가 리턴했던 프로미스 객체는 `fulfilled` 상태가 되고, 그 작업 성공 결과로 `undefined`를 갖게 된다.
- 이전 메서드의 콜백에서 **에러가 발생했다면**  
  -> `then` 메서드가 리턴한 프로미스 객체는 `rejected` 상태가 되고, 그 작업 실패 정보로 해당 `Error` 객체를 갖게 된다.

#### new Promise

비동기 작업을 하는 어떤 함수를 만들고 싶다면 함수 안에 프로미스 객체를 만들어 함수 실행 결과로 프로미스 객체를 리턴하게 만들면 된다.

- `resolve`, `reject`  
  작업 성공 결과에 따라 호출되는 콜백함수이다.

- `then`  
  작업이 성공해서 resolve 함수가 호출되었다면 .then 메서드를 통해 리턴한 데이터에 접근할 수 있다.

```jsx
const func1 = () => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve("func1 작업 끝");
    }, 1000);
  });
};

func1().then((data) => {
  console.log(data);
});
```

### fetch API

서버에 HTTP요청을 보내고 응답을 처리하는 기능을 하는 함수로 대표적인 프로미스 객체를 리턴하는 함수이다.

```jsx
fetch(
  "[https://jsonplaceholder.typicode.com/posts](https://jsonplaceholder.typicode.com/posts)"
).then((response) => {
  return response.json();
});
```

#### Promise chaning

비동기적인 작업을 순차적으로 실행시키기 위해 프로미스 객체에 `then` 메서드를 연속적으로 붙일 수 있다.  
`then` 메서드가 새로운 프로미스 객체를 리턴하기 때문에 `then` 뒤에 또 `then`을 붙일 수 있다.

```jsx
fetch("https://jsonplaceholder.typicode.com/posts")
  .then((response) => {
    return response.json();
  })
  .then((result) => {
    const users = result;
    return users[0];
  })
  .then((user) => {
    const id = user.userId;
    const subject = user.title;
    const content = user.body;

    console.log(id);
    console.log(subject);
    console.log(content);
  });
```

#### catch

프로미스 객체가 `rejected`상태가 되었을때 실행하고 싶은 콜백을 적는 용도로 사용한다.  
`then`메서드의 가장 마지막에 붙이면 된다.

```jsx
.catch((error) => { console.log(error); })
```

`catch`메서드는 사실 이것과 같다

```jsx
.then(undefined ,(error) => { console.log(error); })
```

#### finally

작업의 성공, 실패와 상관없이 실행하고 싶은 코드를 작성할수 있다.  
작업이 성공했는지, 안했는지 상관 없기 때문에 파라미터를 받지 않는다.  
catch 메서드 보다도 뒤에 쓴다.

```jsx
.finally(() => { console.log('작업 완료'); })
```

#### Promise.all()

`promise.all`은 여러개의 비동기 작업을 동시에 시작한다음 그 작업이 전부 다 끝나면 결과를 배열로 리턴한다.  
예를 들어 1초, 3초, 5초의 작업을 `Promise.all`을 사용하여 동시에 처리했을때 가장 오래 걸리는 5초의 작업이 끝났을때 모든 결과를 리턴한다.  
아래의 예제 역시 `func1`, `func2` 를 동시에 실행시켜서 가장 오래 걸리는 `func2` 의 작업시간인 2초가 끝나면 모든 작업이 종료된다.

```jsx
const func1 = () => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve("func1 작업 끝");
    }, 1000);
  });
};

const func2 = () => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve("func2 작업 끝");
    }, 2000);
  });
};

const allFunc = () => {
  return Promise.all([func1(), func2()]);
};

allFunc().then((data) => {
  console.log(data);
});

//['func1 작업 끝', 'func2 작업 끝']
```

#### Promise.all()의 배열에 있는 Promise에 에러가 발생할 경우

나머지 프로미스 객체의 작업 실행 결과와 상관없이 에러가 반환된다

```jsx
const func1 = () => {
  return new Promise((resolve, reject) => {
    resolve("func1 작업 끝");
  });
};

const func2 = () => {
  return new Promise((resolve, reject) => {
    reject("func2 에러");
  });
};

const func3 = () => {
  return new Promise((resolve, reject) => {
    resolve("func3 작업 끝");
  });
};

const allFunc = () => {
  return Promise.all([func1(), func2(), func3()]);
};

allFunc()
  .then((data) => {
    console.log(data);
  })
  .catch((err) => {
    console.log(err);
  });

//func2 에러
```
